### ISSUE TITLE
Printer GUI tries to fetch built in system font that does not exist.

### ISSUE THREAD

**Issue by NordicS** [Insality/defold-printer#6]
On fetching it as a library in Defold, it tries to fetch a font that is no longer there. It tries to use a font `/builtins/fonts/system_font.font` however it cannot be found on built. This can be worked around by just switching it in the editor to the built-in default font. But it is a bit jarring to do it every time. 
Here is the error message.

/printer/printer.gui
	The file '/builtins/fonts/system_font.font' could not be found.

![image](https://github.com/Insality/defold-printer/assets/84878803/b0377430-8d0f-44d9-ae66-a4ad10291ecd)

**Comment by Insality** [comment]
Thanks! Updated
